### ISSUE TITLE
Migration of an issue from Tempest-Wave (How can I add music file to the project in Creator?)

### ISSUE THREAD

**Issue by KYHSGeekCode** [thiEFcat/TempestWave_Rebuilt#5]
https://github.com/thiEFcat/Tempest-Wave/issues/1

@thiEFcat When I click "Music file (음원 파일)" , nothing happens. Do I have to copy the music file manually?

+ are you a memeber of "the" SNU GDC that I know?

**Comment by thiEFcat** [comment]
한국 분이신 것 같으니 한국어로 설명 드리는 편이 더 나을 것 같습니다.

Creator에 음원 파일을 추가하기 위해서는 Tempest Wave의 실행 파일이 있는 폴더에 있는 Creator 폴더 (안드로이드에서는 storage/emulated/0/TempestWave/Creator. 어느 쪽이든 한 번이라도 Creator에 들어갔다면 만들어집니다)에 mp3, wav 형식의 파일을 넣어야 합니다.
게임 설명서(첫 화면의 Introduction 버튼)에 Creator 폴더에 대한 설명이 있고, Creator 화면의 Creator 도움말 또는 게임 설명서에 Creator에서 음원 파일을 추가하는 방법이 설명되어 있습니다.

* 맞습니다. GitHub 호스팅된 프로젝트를 포함한 여러 프로젝트에 참여하고 있습니다.

**Comment by KYHSGeekCode** [comment]
@thiEFcat 감사합니다. PC안에서는 Creator 폴더에 wav 파일 넣어주면 목록에 뜨더라고요.

+ 저는 이번에 입학하게 된 새내기인데 SNU GDC동아리에도 관심을 갖고 있습니다. 미리 반갑습니다!
